server:
  port: 8080

spring:
  application:
    name: target-app
  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:target_app_db}
    username: ${APP_DB_USER:target_user}
    password: ${APP_DB_PASSWORD:target_password}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
